CREATE TABLE ROLE_MASTER_TABLE (id bigint PRIMARY KEY AUTO_INCREMENT ,name VARCHAR(255));
CREATE TABLE USER_MASTER_TABLE (id bigint PRIMARY KEY AUTO_INCREMENT, firstname VARCHAR(255), lastname VARCHAR(255), 
								email VARCHAR(255), password VARCHAR(255));

CREATE TABLE USER_ROLE (
    userid BIGINT,
    roleid BIGINT,
    PRIMARY KEY (userid, roleid),
    FOREIGN KEY (userid) REFERENCES USER_MASTER_TABLE(id),
    FOREIGN KEY (roleid) REFERENCES ROLE_MASTER_TABLE(id)
);
